name: Build and Push to ECR and ACR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag (e.g., latest, 1.0.0)'
        required: true
        default: 'latest'
        type: string

jobs:
  build-and-push:
    name: Build and Push Container Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ECR_BACKEND_REPOSITORY }}:${{ github.event.inputs.image_tag }}
            
      # - name: Login to Azure ACR
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.ACR_LOGIN_SERVER }}
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_REPOSITORY }}:${{ github.event.inputs.image_tag }}

      - name: Checkout deployment repository 
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.DEPLOYMENT_REPO_NAME }} 
          token: ${{ secrets.DEPLOYMENT_REPO_PAT }} 
          path: 'deployment-repo' 

      # - name: Install Kustomize 
      #   run: |
      #     curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
      #     sudo mv kustomize /usr/local/bin/

      # - name: Update Kubernetes manifest
      #   run: |
      #     cd deployment-repo/k8s/shopping-mall/backend/overlays/aws
      #     kustomize edit set image backend-image=${{ secrets.ECR_BACKEND_REPOSITORY }}:${{ github.event.inputs.image_tag }}

      - name: Update values.yaml
        run: | 
          cd deployment-repo
          yq e '.frontend.deployment.tag = "${{ github.event.inputs.image_tag }}"' -i values.yaml

      - name: Commit and push changes
        run: |
          cd deployment-repo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update backend image to tag ${{ github.event.inputs.image_tag }}" || echo "No changes to commit"
          git push